"""adds columns to table

Revision ID: 733a74aaa4e3
Revises: 67f5d67aea55
Create Date: 2024-10-07 20:56:45.151169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733a74aaa4e3'
down_revision = '67f5d67aea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
